[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.81"
reqwest = { version = "0.12.5", features = ["blocking", "json"] }
anyhow = "1.0.86"
thiserror = "1.0.61"
serde_json = "1.0"
lazy_static = "1.5.0"
futures = "0.3.30"
