[package]
name = "models"
version = "0.1.0"
edition = "2021"

[dependencies]
api = { path = "../api" }
serde = { version = "1.0.204", features = ["derive"] }


[dev-dependencies]
tokio = { version = "1.38.0", features = ["full"] }
anyhow = "1.0.86"
